### PR TITLE
Update to 2.13

### PR DESCRIPTION
**Pull request by johnynek**
add a 2.13 CI check and update scalatest to a version that works with 2.13.

### CODE REVIEW

**Comment by johnynek** [comment]
part of #29

**Comment by johnynek** [comment]
looks like no travis, but I tested 2.11, 2.12 and 2.13 on my machine.

**Comment by johnynek** [comment]
@thomas-stripe do you know why travis isn't being triggered?

**Comment by tixxit** [comment]
Not sure why it isn't :\ I'll figure it out later though.

**Comment by johnynek** [comment]
Thanks for taking a look!

**Pull request merged**
